// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameVideo = "video"

// Video mapped from table <video>
type Video struct {
	ID          int64     `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true" json:"id"`
	AuthorID    int64     `gorm:"column:author_id;type:bigint;not null;index:idx_video_author_id,priority:1;comment:作者信息" json:"author_id"` // 作者信息
	PlayURL     string    `gorm:"column:play_url;type:varchar(255);not null;comment:播放地址" json:"play_url"`                                  // 播放地址
	CoverURL    string    `gorm:"column:cover_url;type:varchar(255);not null;comment:封面地址" json:"cover_url"`                                // 封面地址
	PublishTime time.Time `gorm:"column:publish_time;type:datetime;not null;comment:发布时间" json:"publish_time"`                              // 发布时间
	Title       string    `gorm:"column:title;type:varchar(255);not null;comment:标题" json:"title"`                                          // 标题
}

// TableName Video's table name
func (*Video) TableName() string {
	return TableNameVideo
}
