linters:
  enable-all: false
  disable-all: true
  fast: false
  enable:
#    - errcheck
#    - bodyclose
#    - dogsled
#    - dupl
#    - exportloopref
#    - exhaustive
#    - goconst
#    - gocritic
#    - gocyclo
#    - gofmt
#    - goimports
#    - goprintffuncname
#    - gosec
#    - gosimple
#    - govet
#    - ineffassign
#    - lll
#    - misspell
#    - nakedret
#    - noctx
#    - nolintlint
#    - staticcheck
#    - stylecheck
#    - typecheck
#    - unconvert
#    - unparam
    - unused
    - whitespace
#    - gofumpt

run:
  timeout: 3m
