// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"fmt"
	"testing"

	"github.com/Biu-X/TikTok/dal/model"
	"gorm.io/gen"
	"gorm.io/gen/field"
	"gorm.io/gorm/clause"
)

func init() {
	InitializeDB()
	err := db.AutoMigrate(&model.Message{})
	if err != nil {
		fmt.Printf("Error: AutoMigrate(&model.Message{}) fail: %s", err)
	}
}

func Test_messageQuery(t *testing.T) {
	message := newMessage(db)
	message = *message.As(message.TableName())
	_do := message.WithContext(context.Background()).Debug()

	primaryKey := field.NewString(message.TableName(), clause.PrimaryKey)
	_, err := _do.Unscoped().Where(primaryKey.IsNotNull()).Delete()
	if err != nil {
		t.Error("clean table <message> fail:", err)
		return
	}

	_, ok := message.GetFieldByName("")
	if ok {
		t.Error("GetFieldByName(\"\") from message success")
	}

	err = _do.Create(&model.Message{})
	if err != nil {
		t.Error("create item in table <message> fail:", err)
	}

	err = _do.Save(&model.Message{})
	if err != nil {
		t.Error("create item in table <message> fail:", err)
	}

	err = _do.CreateInBatches([]*model.Message{{}, {}}, 10)
	if err != nil {
		t.Error("create item in table <message> fail:", err)
	}

	_, err = _do.Select(message.ALL).Take()
	if err != nil {
		t.Error("Take() on table <message> fail:", err)
	}

	_, err = _do.First()
	if err != nil {
		t.Error("First() on table <message> fail:", err)
	}

	_, err = _do.Last()
	if err != nil {
		t.Error("First() on table <message> fail:", err)
	}

	_, err = _do.Where(primaryKey.IsNotNull()).FindInBatch(10, func(tx gen.Dao, batch int) error { return nil })
	if err != nil {
		t.Error("FindInBatch() on table <message> fail:", err)
	}

	err = _do.Where(primaryKey.IsNotNull()).FindInBatches(&[]*model.Message{}, 10, func(tx gen.Dao, batch int) error { return nil })
	if err != nil {
		t.Error("FindInBatches() on table <message> fail:", err)
	}

	_, err = _do.Select(message.ALL).Where(primaryKey.IsNotNull()).Order(primaryKey.Desc()).Find()
	if err != nil {
		t.Error("Find() on table <message> fail:", err)
	}

	_, err = _do.Distinct(primaryKey).Take()
	if err != nil {
		t.Error("select Distinct() on table <message> fail:", err)
	}

	_, err = _do.Select(message.ALL).Omit(primaryKey).Take()
	if err != nil {
		t.Error("Omit() on table <message> fail:", err)
	}

	_, err = _do.Group(primaryKey).Find()
	if err != nil {
		t.Error("Group() on table <message> fail:", err)
	}

	_, err = _do.Scopes(func(dao gen.Dao) gen.Dao { return dao.Where(primaryKey.IsNotNull()) }).Find()
	if err != nil {
		t.Error("Scopes() on table <message> fail:", err)
	}

	_, _, err = _do.FindByPage(0, 1)
	if err != nil {
		t.Error("FindByPage() on table <message> fail:", err)
	}

	_, err = _do.ScanByPage(&model.Message{}, 0, 1)
	if err != nil {
		t.Error("ScanByPage() on table <message> fail:", err)
	}

	_, err = _do.Attrs(primaryKey).Assign(primaryKey).FirstOrInit()
	if err != nil {
		t.Error("FirstOrInit() on table <message> fail:", err)
	}

	_, err = _do.Attrs(primaryKey).Assign(primaryKey).FirstOrCreate()
	if err != nil {
		t.Error("FirstOrCreate() on table <message> fail:", err)
	}

	var _a _another
	var _aPK = field.NewString(_a.TableName(), clause.PrimaryKey)

	err = _do.Join(&_a, primaryKey.EqCol(_aPK)).Scan(map[string]interface{}{})
	if err != nil {
		t.Error("Join() on table <message> fail:", err)
	}

	err = _do.LeftJoin(&_a, primaryKey.EqCol(_aPK)).Scan(map[string]interface{}{})
	if err != nil {
		t.Error("LeftJoin() on table <message> fail:", err)
	}

	_, err = _do.Not().Or().Clauses().Take()
	if err != nil {
		t.Error("Not/Or/Clauses on table <message> fail:", err)
	}
}
