name: CI-Test

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - LICENSE
  pull_request:
    paths-ignore:
      - '**.md'
      - LICENSE
  workflow_dispatch:

jobs:
  CI-Test:
    strategy:
      matrix:
        os-version: [ "ubuntu-latest" ]

    runs-on: ${{ matrix.os-version }}
    steps:
    - uses: actions/checkout@v3

    - name: Set up FFmpeg
      uses: FedericoCarboni/setup-ffmpeg@v2
      id: setup-ffmpeg

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        architecture: x64

    - name: Set up CoverSnap
      run: |
        python -m pip install --upgrade pip
        pip install coversnap

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Set up MySQL
      uses: ankane/setup-mysql@v1

    - name: Set up Redis
      uses: supercharge/redis-github-action@1.6.0
      with:
        redis-password: '123456'

    - name: Test
      run: go test -v ./...
