name: CI-Test

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - LICENSE
  pull_request:
    paths-ignore:
      - '**.md'
      - LICENSE
  workflow_dispatch:

jobs:
  CI-Test:
    strategy:
      matrix:
        os-version: [ "ubuntu-latest" ]

    runs-on: ${{ matrix.os-version }}
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Set up MySQL
      uses: ankane/setup-mysql@v1

    - name: Set up Redis
      uses: supercharge/redis-github-action@1.6.0
      with:
        redis-password: '123456'

    - name: Test
      run: go test -v ./...
