name: CI-Test

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - LICENSE
  pull_request:
    paths-ignore:
      - '**.md'
      - LICENSE
  workflow_dispatch:

jobs:
  CI-Test:
    strategy:
      matrix:
        os-version: [ "ubuntu-20.04" ]

    runs-on: ${{ matrix.os-version }}
    steps:
      - uses: actions/checkout@v3

      - name: Set up FFmpeg
        uses: FedericoCarboni/setup-ffmpeg@v2
        id: setup-ffmpeg

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          architecture: x64

      - name: Install CoverSnap and MySQL Connector
        run: |
          python -m pip install --upgrade pip
          pip install coversnap mysql-connector-python

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: Set up Docker
        uses: docker/setup-buildx-action@v1

      - name: Set up Redis Docker
        run: |
          docker pull redis:latest
          docker run -d --name redis -p 6379:6379 redis --requirepass 123456

      - name: Set up MySQL
        run: |
          docker pull mysql:latest
          docker run -d --name mysql -p 3306:3306 -e MYSQL_ROOT_PASSWORD=123456 mysql

      - name: Create MySQL Database and Table
        run: |
          sleep 10
          cd script
          python CreateMySQL.py

      - name: Test
        run: go test ./...
